### ISSUE TITLE
Rename _storage private field to be different in each class

### ISSUE THREAD

**Issue by kevmoo** [johnmccutchan/vector_math#126]
Vector2: _v2st
Vector3: _v3st

Matrix2: _m2st
Matrix3: _m3st

etc

Will help dart2js create smaller code

CC @Fox32

**Comment by Fox32** [comment]
@kevmoo Yes, that will be the next PR I will send. However, I have to wait till #124 is merged as it would otherwise result in merge conflicts.

**Comment by Fox32** [comment]
@kevmoo I tried to it right now. One could think that this is a quick change using the refactoring feature of the Dart Editor. However when I use the rename function in the Dart Editor ( 1.10.0.dev_01_00 (DEV) ) it randomly change other files too that aren't related at all. Could you try if you can reproduce this and maybe help the analyzer team to fix that?

**Comment by kevmoo** [comment]
I'll take a look. Thanks!

**Comment by Fox32** [comment]
Btw. I'm on Windows and tried to reanalyzer everything multiple times without any improvement. The latest release is also affected 1.10.0.dev_01_01.

Example: If I rename Vector2._storage to _storage2 line 104 of matrix4 is also modified (and many more). It shows the same behavior if I revert everything and try it again.

**Comment by kevmoo** [comment]
https://code.google.com/p/dart/issues/detail?id=23189

This works great in IntelliJ. I'm happy to pull this off quick.

**Comment by Fox32** [comment]
@kevmoo Thanks! I will wait with this till it's fixed. That it's much less work :)
