### ISSUE TITLE
Please consider pull request #83

### ISSUE THREAD

**Issue by udhos** [johnmccutchan/vector_math#85]
John,

Please consider merging https://github.com/johnmccutchan/vector_math/pull/83

Make setRotationMatrix() compatible, in respect to inversion, with setViewMatrix().
Add helper setModelMatrix().
Add slightly simpler/faster setViewMatrix2().
  setViewMatrix(RunTime): 118.21728336682823 us.
  setViewMatrix2(RunTime): 73.02201613786556 us.

Thanks,
Everton

**Comment by johnmccutchan** [comment]
Commented on it.
