### ISSUE TITLE
VectorX.normalizeLength isn't doing what it says in the description

### ISSUE THREAD

**Issue by Fox32** [johnmccutchan/vector_math#88]
I have fixed it in my PR, but I don't think that it will ever get merged, thererfore it post this issue here so that it don't get lost:

Vector2/3/4.normalizeLength() documentation says that it returns the length before normalizing, however it returns the inverse of the previous length.

A fix can be found here: https://github.com/Fox32/vector_math/commit/66b9578663c4258241bc273803dc9dbafdb1abd2

**Comment by johnmccutchan** [comment]
@Fox32 Could you post a pull request (with a test) which fixes just this bug?

**Comment by Fox32** [comment]
@johnmccutchan Done
